USE hotc


IF NOT EXISTS(SELECT * FROM HOT_USERS WHERE NETWORK_LOGIN = 'aguedea')
INSERT INTO HOT_USERS
	(NETWORK_LOGIN, FIRST_NAME, LAST_NAME)
VALUES ('aguedea', 'ALEX', 'GUEDEA')

IF NOT EXISTS(SELECT * FROM HOT_USERS WHERE NETWORK_LOGIN = 'nquan')
INSERT INTO HOT_USERS
	(NETWORK_LOGIN, FIRST_NAME, LAST_NAME)
VALUES	('nquan', 'NGA', 'QUAN')

