USE ADDR;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT EXECUTE ON ADDR.dbo.bpChkDelPartyRec TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpChkDelCntctRec TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelAffilParty TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelAffilCntct TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelCntctPer TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelCntctRec TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelLustAffilCntcts TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelOrg TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpDelMailAddr TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsAffilCntct TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsAffilParty TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsCntctPer TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsLUSTAffilCntcts TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsMailAddr TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpInsOrg TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpUpdCntctPer TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpUpdLUSTAffilCntcts TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpUpdMailAddr TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpUpdOrg TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpUpdPartyCntct TO LUSTUser;
GRANT EXECUTE ON ADDR.dbo.bpGenPartyId TO LUSTUser;
GRANT SELECT ON ADDR.dbo.LUSTAffilCntcts TO LUSTUser;
GRANT DELETE ON ADDR.dbo.LUSTAFfilCntcts TO LUSTUSer;
GRANT SELECT ON ADDR.dbo.ContactPerson TO LUSTUser;
GRANT DELETE ON ADDR.dbo.ContactPerson TO LUSTUser;
GRANT SELECT ON ADDR.dbo.vDEQAffilParty TO LUSTUser;
GRANT INSERT ON ADDR.dbo.ArchAffilParty TO LUSTUser;
GRANT DELETE ON ADDR.dbo.AffilParty TO LUSTUser;
GRANT INSERT ON ADDR.dbo.ArchAffilContacts TO LUSTUser;
GRANT SELECT ON ADDR.dbo.AffilContacts TO LUSTUser;
GRANT DELETE ON ADDR.dbo.AffilContacts TO LUSTUser;
GRANT INSERT ON ADDR.dbo.ArchContactPerson TO LUSTUser;
GRANT INSERT ON ADDR.dbo.ArchOrganization TO LUSTUser;
GRANT SELECT ON ADDR.dbo.Organization TO LUSTUser;
GRANT DELETE ON ADDR.dbo.Organization TO LUSTUser;
GRANT SELECT ON ADDR.dbo.MailAddress TO LUSTUser;
GRANT INSERT ON ADDR.dbo.ArchMailAddress TO LUSTUser;
GRANT DELETE ON ADDR.dbo.MailAddress TO LUSTUser;



USE AGENCY;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;


GRANT INSERT ON	AGENCY.dbo.Affiliation TO LUSTUser;
GRANT DELETE ON	AGENCY.dbo.Affiliation TO LUSTUser;
GRANT SELECT ON	AGENCY.dbo.Affiliation TO LUSTUser;
GRANT UPDATE ON	AGENCY.dbo.Affiliation TO LUSTUser;
GRANT SELECT ON AGENCY.dbo.AffiliationNames TO LUSTUser;
GRANT DELETE ON AGENCY.dbo.AffiliationNames TO LUSTUser;
GRANT INSERT ON AGENCY.dbo.DelAffilNames TO LUSTUser;
GRANT INSERT ON AGENCY.dbo.DelAffiliation TO LUSTUser;
GRANT SELECT ON AGENCY.dbo.COUNTIES TO LUSTUSER;
GRANT SELECT ON AGENCY.dbo.AffilTypes TO LUSTUSER;
GRANT SELECT ON AGENCY.DBO.FACA_GEO_LOC TO LUSTUSER;
GRANT SELECT ON AGENCY.DBO.STATES TO LUSTUSER;
GRANT SELECT ON AGENCY.DBO.PLACES TO LUSTUSER;
GRANT SELECT ON AGENCY.dbo.DEQRegions TO LUSTUSER;
GRANT SELECT ON AGENCY.dbo.cities TO LUSTUSER;
GRANT EXECUTE ON AGENCY.dbo.bpDelAffil TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.bpInsAffiliation TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.bpInsAffilName TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.bpUpdAffilName TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.bpUpdAffiliation TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.apGetUserEmpID TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.bpDelAffil TO LUSTUser;
GRANT EXECUTE ON AGENCY.dbo.fnLoginErrMsg TO LUSTUser;


USE ATAS;

IF EXISTS (SELECT 1 WHERE SCHEMA_ID('LustUser') IS NOT NULL)
	DROP SCHEMA [LUSTUser]

IF EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	DROP USER [lustuser];

CREATE USER [LUSTUser] FOR LOGIN [lustuser];

ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON ATAS.dbo.PROJECT TO LUSTUser;
GRANT SELECT ON ATAS.dbo.TmcntrPgmVw TO LUSTUser;


USE CRIS;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON CRIS.dbo.Project TO LUSTUser;
GRANT SELECT ON CRIS.dbo.ResponsibleParty TO LUSTUser;
GRANT SELECT ON CRIS.dbo.vwCRISParty TO LUSTUser;



USE HOTC;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT EXECUTE ON dbo.apGetCleanDecommByHotIdData TO LUSTUSER;
GRANT EXECUTE ON dbo.apGetHotcContacts TO LUSTUSER;
GRANT EXECUTE ON dbo.apGetHOTServiceProviderData TO LUSTUSER;
GRANT EXECUTE ON dbo.apGetLustManagementData TO LUSTUSER;
GRANT EXECUTE ON dbo.apGetSearchHOTC_LUSTData TO LUSTUSER;
GRANT EXECUTE ON dbo.apInsUpdHotcCleanDecommData TO LUSTUSER;
GRANT EXECUTE ON dbo.apInsUpdHotcLustData TO LUSTUSER;
GRANT EXECUTE ON dbo.apInsUpdHotcManagementData TO LUSTUSER;
GRANT EXECUTE ON dbo.apValidateLUSTLogNumberData TO LUSTUSER;
GRANT EXECUTE ON dbo.apValidateLogNumberAndManagementData TO LUSTUSER;
GRANT INSERT ON dbo.HOT_DECOMMISSION TO LUSTUSER;
GRANT SELECT ON dbo.HOT_DECOMMISSION TO LUSTUSER;
GRANT UPDATE ON dbo.HOT_DECOMMISSION TO LUSTUSER;
GRANT INSERT ON dbo.HOT_MANAGEMENT TO LUSTUSER;
GRANT SELECT ON dbo.HOT_MANAGEMENT TO LUSTUSER;
GRANT UPDATE ON dbo.HOT_MANAGEMENT TO LUSTUSER;



USE HRIS;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON HRIS.dbo.vWQEmpTbl TO LUSTUSER;
GRANT SELECT ON HRIS.dbo.EmpHisInitVw TO LUSTUSER;
GRANT SELECT ON HRIS.dbo.vAddrEmpTbl TO LUSTUSER;
GRANT SELECT ON HRIS.dbo.vActiveEmpTbl TO LUSTUSER;


USE LICENSING;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON Licensing.dbo.vUST_PersonInfo TO LUSTUSER;
GRANT SELECT ON Licensing.dbo.vUST_LicenseInfo TO LUSTUSER;



USE LIT;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT EXECUTE ON LIT.dbo.apGetLITProcessStatus TO LUSTUSER;
GRANT EXECUTE ON LIT.dbo.apRetrieveGeoLocID TO LUSTUSER;
GRANT SELECT ON LIT.dbo.FacilityLocation  TO LUSTUSER;
GRANT SELECT ON LIST.dbo.FACA_GEO_LOC TO ACCESS1;

USE MSDB;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT EXECUTE ON msdb.dbo.sp_send_dbmail TO LUSTUSER;



USE UST;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON UST.dbo.Facility TO LUSTUSER; 
GRANT SELECT ON UST.dbo.Tank TO LUSTUSER;
GRANT SELECT ON UST.dbo.USTUsers TO LUSTUSER;
GRANT SELECT ON UST.dbo.Permit TO LUSTUSER;
GRANT SELECT ON UST.dbo.PermitStatusType TO LUSTUSER;
GRANT SELECT ON UST.dbo.TankSubstance TO LUSTUSER;
GRANT SELECT ON UST.dbo.ComplianceInspection TO LUSTUSER;


USE WQSIS;
IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT SELECT ON WQSIS.dbo.WQFacility TO LUSTUSER;


USE LUST;

IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N'LUSTUser')
	CREATE USER [LUSTUser] FOR LOGIN [lustuser]
ALTER USER [LUSTUser] WITH DEFAULT_SCHEMA=[dbo]

ALTER USER LUSTUser WITH LOGIN = LUSTUser;

GRANT EXECUTE ON LUST.dbo.apGetOLPRRLookupTables TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetLookupTablesByType TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apWorkReportedBySearch TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apOLPRRInsertIncident TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.ApDltSiteNameAlias TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetCountyIdAndNameFromZP4Fips TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetCurrentProjMgr TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetLogNumber TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apDltIncidentByLustId TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetAssessmentSiteScoreValuesByLustId TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apGetAssessmentAllByLustId TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apUpdateSiteScore TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apOLPRRGetIncidentById TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apOLPRRGetContactByIdByContactType TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apOLPRRGetIncidents TO LUSTUSER;
GRANT EXECUTE ON LUST.dbo.apDltLUSTContactByAffilIDData TO LUSTUSER;
GRANT UPDATE ON LUST.dbo.Management TO LUSTUSER;
GRANT INSERT ON LUST.dbo.Management TO LUSTUSER;
GRANT SELECT ON LUST.dbo.vwLUSTParty TO LUSTUSER;

