
USE [LUST]
GO

/****** Object:  Table [dbo].[DebugTable]    Script Date: 6/18/2019 10:54:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DebugTable](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[InsertTime] [datetime] NULL,
	[Message] [varchar](1024) NULL,
 CONSTRAINT [PK_DebugTable] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DebugTable] ADD  DEFAULT (getdate()) FOR [InsertTime]
GO


GRANT INSERT ON [dbo].[DebugTable] TO [LUSTUser] AS [dbo]
GO

