USE lust
UPDATE OLPRRContractors
	SET UID = 'CORIN', 
		PWD = 'SALNAVE',
		EMAIL_ADDRESS = 'SALNAVE.CORIN@DEQ.STATE.OR.US',
		COMPANY_CONTACT_NAME = 'CORIN SALNAVE',
		COMPANY_CONTACT_PHONE_NUMBER = '503-229-5049'
WHERE OlprrContractorsId = 320



